replicaCount: 1
image:
  repository: pdt1991/go-web-app
  pullPolicy: IfnotPresent
  tag: "10625211199"

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
